# .travis.yml
language: ruby
cache: 
  bundler: true
  apt: true
addons:
  - postgresql: "9.3"
rvm:
  - 2.1.2
before_install:
  - gem update --system
script:
  - RAILS_ENV=test bundle exec rake db:drop db:create db:schema:load 
  - mkdir -p tmp/cache
  - bundle exec rake db:test:prepare
  - bundle exec rake test
env:
  - DATABASE=postgresql