---
site_name: El Carchi
publisher:
  name: Prefectura del Carchi
  address: 
email_addresses:
  from: hola@alabs.org
  contact: hola@alabs.org
  proposal_moderators: hola@alabs.org
  orphan_videos_responsibles: hola@alabs.org
social_networks:
  twitter: https://twitter.com/GADCarchi
  facebook: http://www.facebook.com/pages/Irekia/416723460540
  flickr: http://www.flickr.com/photos/irekia
  youtube: http://www.youtube.com/irekia
optional_modules:
  proposals: true
  debates: true
  streaming: false
  headlines: false
customized: true
