---
site_name: Gobierno Abierto del Carchi
publisher:
  name: Prefectura del Carchi
  address: 
email_addresses:
  from: hola@alabs.org
  contact: hola@alabs.org
  proposal_moderators: hola@alabs.org
  orphan_videos_responsibles: hola@alabs.org
social_networks:
  twitter: https://twitter.com/GADCarchi
  facebook: https://www.facebook.com/carchiprefectura
  flickr: https://www.facebook.com/carchiprefectura
  youtube: https://www.youtube.com/channel/UCtXoKjyUKo8leh_R227zLQQ
optional_modules:
  proposals: true
  debates: true
  streaming: true
  headlines: false
customized: true
