---
site_name: Carchi
publisher:
  name: Prefectura del Carchi
  address: Embajadores, 35
email_addresses:
  from: apardo@alabs.org
  contact: apardo@alabs.org
  proposal_moderators: apardo@alabs.org
  orphan_videos_responsibles: apardo@alabs.org
social_networks:
  twitter: https://twitter.com/irekia
  facebook: http://www.facebook.com/pages/Irekia/416723460540
  flickr: http://www.flickr.com/photos/irekia
  youtube: http://www.youtube.com/irekia
optional_modules:
  proposals: true
  debates: true
  streaming: false
  headlines: false
customized: true
